// Code generated by "stringer -type=CoolingCycle"; DO NOT EDIT.

package ti

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CCCalc-0]
	_ = x[CCOpen-1]
	_ = x[CCClosed-2]
}

const _CoolingCycle_name = "CCCalcCCOpenCCClosed"

var _CoolingCycle_index = [...]uint8{0, 6, 12, 20}

func (i CoolingCycle) String() string {
	if i < 0 || i >= CoolingCycle(len(_CoolingCycle_index)-1) {
		return "CoolingCycle(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CoolingCycle_name[_CoolingCycle_index[i]:_CoolingCycle_index[i+1]]
}
