// Code generated by "stringer -type=DriveClassification"; DO NOT EDIT.

package ti

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DCChemical-0]
	_ = x[DCElectrothermal-1]
	_ = x[DCElectromagnetic-2]
	_ = x[DCElectrostatic-3]
	_ = x[DCFissionThermal-4]
	_ = x[DCFissionPulse-5]
	_ = x[DCFusionThermal-6]
	_ = x[DCFusionPulse-7]
	_ = x[DCAntimatter-8]
}

const _DriveClassification_name = "DCChemicalDCElectrothermalDCElectromagneticDCElectrostaticDCFissionThermalDCFissionPulseDCFusionThermalDCFusionPulseDCAntimatter"

var _DriveClassification_index = [...]uint8{0, 10, 26, 43, 58, 74, 88, 103, 116, 128}

func (i DriveClassification) String() string {
	if i < 0 || i >= DriveClassification(len(_DriveClassification_index)-1) {
		return "DriveClassification(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DriveClassification_name[_DriveClassification_index[i]:_DriveClassification_index[i+1]]
}
