// Code generated by "stringer -type=Propellant"; DO NOT EDIT.

package ti

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PropReactionProducts-0]
	_ = x[PropAnything-1]
	_ = x[PropHydrogen-2]
	_ = x[PropWater-3]
	_ = x[PropNobleGases-4]
	_ = x[PropVolatiles-5]
	_ = x[PropMetals-6]
}

const _Propellant_name = "PropReactionProductsPropAnythingPropHydrogenPropWaterPropNobleGasesPropVolatilesPropMetals"

var _Propellant_index = [...]uint8{0, 20, 32, 44, 53, 67, 80, 90}

func (i Propellant) String() string {
	if i < 0 || i >= Propellant(len(_Propellant_index)-1) {
		return "Propellant(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Propellant_name[_Propellant_index[i]:_Propellant_index[i+1]]
}
